// This file will be auto-generated by running: supabase gen types typescript --local
// For now, we'll use a basic Database type structure

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'admin' | 'editor' | 'author' | 'reader'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'admin' | 'editor' | 'author' | 'reader'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'admin' | 'editor' | 'author' | 'reader'
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          parent_id: string | null
          color: string | null
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          parent_id?: string | null
          color?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          parent_id?: string | null
          color?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      articles: {
        Row: {
          id: string
          title: string
          slug: string
          excerpt: string | null
          content: any
          featured_image: string | null
          author_id: string
          category_id: string | null
          status: 'draft' | 'published' | 'archived'
          published_at: string | null
          reading_time: number
          view_count: number
          meta_title: string | null
          meta_description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          excerpt?: string | null
          content: any
          featured_image?: string | null
          author_id: string
          category_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          reading_time?: number
          view_count?: number
          meta_title?: string | null
          meta_description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          excerpt?: string | null
          content?: any
          featured_image?: string | null
          author_id?: string
          category_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          reading_time?: number
          view_count?: number
          meta_title?: string | null
          meta_description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          created_at?: string
        }
      }
      filters: {
        Row: {
          id: string
          name: string
          slug: string
          parent_id: string | null
          level: number
          order_index: number
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          parent_id?: string | null
          level?: number
          order_index?: number
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          parent_id?: string | null
          level?: number
          order_index?: number
          description?: string | null
          created_at?: string
        }
      }
      article_tags: {
        Row: {
          article_id: string
          tag_id: string
        }
        Insert: {
          article_id: string
          tag_id: string
        }
        Update: {
          article_id?: string
          tag_id?: string
        }
      }
      article_filters: {
        Row: {
          article_id: string
          filter_id: string
        }
        Insert: {
          article_id: string
          filter_id: string
        }
        Update: {
          article_id?: string
          filter_id?: string
        }
      }
      newsletter_subscribers: {
        Row: {
          id: string
          email: string
          status: 'active' | 'unsubscribed' | 'bounced'
          subscribed_at: string
          unsubscribed_at: string | null
          preferences: any
          source: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          status?: 'active' | 'unsubscribed' | 'bounced'
          subscribed_at?: string
          unsubscribed_at?: string | null
          preferences?: any
          source?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          status?: 'active' | 'unsubscribed' | 'bounced'
          subscribed_at?: string
          unsubscribed_at?: string | null
          preferences?: any
          source?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_view_count: {
        Args: {
          article_id: string
        }
        Returns: undefined
      }
      calculate_reading_time: {
        Args: {
          content_text: string
        }
        Returns: number
      }
      generate_slug: {
        Args: {
          title_text: string
        }
        Returns: string
      }
      get_filter_article_count: {
        Args: {
          filter_id: string
        }
        Returns: number
      }
    }
    Enums: {
      user_role: 'admin' | 'editor' | 'author' | 'reader'
      article_status: 'draft' | 'published' | 'archived'
      subscription_status: 'active' | 'unsubscribed' | 'bounced'
    }
  }
}