import type { Metadata } from "next";
import { Manrope, Caveat } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

const accent = Caveat({
  variable: "--font-accent",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(){try{var t=localStorage.getItem('theme');var m=window.matchMedia('(prefers-color-scheme: dark)').matches;var d=t==='dark'||(!t&&m);var e=document.documentElement.classList;e[d?'add':'remove']('dark')}catch(e){}}();`,
          }}
        />
      </head>
      <body
        className={`${manrope.variable} ${accent.variable} antialiased bg-white text-gray-900 dark:bg-[#0b0b12] dark:text-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
